---
driver:
  # name: docker
  # use_sudo: false
  name: dokken
  chef_version: latest

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: centos:7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[aar_cookbook::web]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
